### ISSUE TITLE
跑npm start出错

### ISSUE THREAD

**Issue by hobbyLin** [wxyyxc1992/create-webpack-app#10]
Failed to compile.                                                                                                                              
 Error in ./src/client.js                                                                                                                     
 Module build failed: Error: Couldn't find preset "flow" relative to directory "/Users/doublewood/Desktop/myProject/dev-config/tool"             
   at Array.map (native)  
dev-config/tool下面的 .babelrc
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "stage-0",
    "flow"
  ],

**Comment by hobbyLin** [comment]
已经解决  你pkg里面没有加babel-preset-flow

npm install --save-dev babel-preset-flow

**Comment by wxyyxc1992** [comment]
Thanks
