### ISSUE TITLE
Cannot find module 'prepack'

### ISSUE THREAD

**Issue by sunhaikuo** [wxyyxc1992/create-webpack-app#13]
复制步骤是：
+ 平台：macOS Sierra
+ 下载源码
+ cd ./vue
+ yarn install
+ npm start
+ 出现： Cannot find module 'prepack'

### 请问：这个怎么解决？

**Comment by wxyyxc1992** [comment]
yarn add prepack -D

或者全局安装 Prepack 试试

yarn global add prepack

**Comment by wxyyxc1992** [comment]
如果有需要麻烦 Reopen
