### ISSUE TITLE
windows平台的install.bat都是错

### ISSUE THREAD

**Issue by vipcxj** [wxyyxc1992/create-webpack-app#5]
疑似直接把sh换了个后缀~
首先换行符得换成windows的，其次注释语法是错的，导致没有一条命令可以运行。最后第一行那个在windows上不只是不起作用，还会报错。
还有个问题可能也会影响其他平台。最开始用npm安装yarn，官方已经废弃的，官方推荐直接用安装包管理器下载安装，或者在windows平台上直接下个msi安装包安装。我的情况是我已经用msi安装了2.3版本的，用了这个install，再次用npm安装了2.2版本的。我也不知道会不会有什么副作用，所以手动用npm卸载了npm内部的yarn

**Comment by wxyyxc1992** [comment]
是啊是啊，确实很多错误，多谢纠正
