### ISSUE TITLE
请教下entry和output怎么对应的

### ISSUE THREAD

**Issue by vipcxj** [wxyyxc1992/create-webpack-app#6]
如题，我查阅各种资料，都说output的js文件名和entry是一一对应的。但是这个脚手架里的配置中，开发模式下，entry是个数组，output用的是[name].bundle.js，但最终文件却是main.bundile.js和vendor.bundle.js，这是怎么回事？到底是哪里配置出来的？
我想将这个项目https://github.com/react-cosmos整合进工程中，但疑似因为index.html和bundle.js的原因杯具了

**Comment by wxyyxc1992** [comment]
main.bundile.js和vendor.bundle.js 是 npm start 的时候才出现，npm run build 的时候不会出现吧
