### ISSUE TITLE
better-npm-run报错

### ISSUE THREAD

**Issue by walkinMrwang** [wxyyxc1992/create-webpack-app#8]
better-npm-run 不是内部或者外部命令，也不是可运行程序
在install后出现的报错

**Comment by wxyyxc1992** [comment]
```
npm install better-npm-run -g
```

**Comment by walkinMrwang** [comment]
[
![1500602894 1](https://user-images.githubusercontent.com/26135370/28446334-ab49dad2-6dfc-11e7-9e77-aed2edb96f66.png)
](url)
npm install better-npm-run -g 后
[
![1500602918 1](https://user-images.githubusercontent.com/26135370/28446347-c9304cde-6dfc-11e7-8dba-c167ddf22e92.png)
](url)

**Comment by ChiaJune** [comment]
+1
